import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
    <html lang="en">
      <body>
        <Header />

        <div className="flex min-h-screen min-w-0">
          <Sidebar />

          <div className="min-w-0 flex-1 overflow-y-auto bg-gray-100 px-2 py-3 scrollbar-hide sm:p-4">
            {children}
          </div>
        </div>

        <Toaster position="top-center" />
      </body>
    </html>
  </ClerkProvider>
);
}